### TASK 1
80 CEREALS
If you like to eat cereal, do yourself a favor and avoid this dataset at all 
costs. After seeing these data it will never be the same for me to eat Fruity 
Pebbles again.
• Do an explained data analysis

### Import Python Packages for Data Analysis

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso

### Upload CognoRise_Cereal Dataset

In [2]:
Cereal = pd.read_csv('CognoRise_Cereal.csv')
Cereal

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

## Get Info about the Dataset

In [3]:
Cereal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      77 non-null     object
 1   mfr       77 non-null     object
 2   type      77 non-null     object
 3   calories  77 non-null     int64
 4   protein   77 non-null     int64
 5   fat       77 non-null     int64
 6   sodium    77 non-null     int64
 7   fiber     77 non-null     float64
 8   carbo     77 non-null     float64
 9   sugars    77 non-null     int64
 10  potass    77 non-null     int64
 11  vitamins  77 non-null     int64
 12  shelf     77 non-null     int64
 13  weight    77 non-null     float64
 14  cups      77 non-null     float64
 15  rating    77 non-null     float64
dtypes: float64(5), int64(8), object(3)
memory usage: 9.8+ KB

### Describe the Dataset

In [4]:
Cereal.describe

<bound method NDFrame.describe of                          name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C        70        4    1     130   10.0
1           100% Natural Bran   Q    C       120        3    5      15    2.0
2                    All-Bran   K    C        70        4    1     260    9.0
3   All-Bran with Extra Fiber   K    C        50        4    0     140   14.0
4              Almond Delight   R    C       110        2    2     200    1.0
..                        ...  ..  ...       ...      ...  ...     ...    ...
72                    Triples   G    C       110        2    1     250    0.0
73                       Trix   G    C       110        1    1     140    0.0
74                 Wheat Chex   R    C       100        3    1     230    3.0
75                   Wheaties   G    C       100        3    1     200    3.0
76        Wheaties Honey Gold   G    C       110        2    1     200    1.0

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating
0     5.0       6     280        25      3     1.0  0.33  68.402973
1     8.0       8     135         0      3     1.0  1.00  33.983679
2     7.0       5     320        25      3     1.0  0.33  59.425505
3     8.0       0     330        25      3     1.0  0.50  93.704912
4    14.0       8      -1        25      3     1.0  0.75  34.384843
..    ...     ...     ...       ...    ...     ...   ...        ...
72   21.0       3      60        25      3     1.0  0.75  39.106174
73   13.0      12      25        25      2     1.0  1.00  27.753301
74   17.0       3     115        25      1     1.0  0.67  49.787445
75   17.0       3     110        25      1     1.0  1.00  51.592193
76   16.0       8      60        25      1     1.0  0.75  36.187559

[77 rows x 16 columns]>

### Get Sum of -1

In [5]:
(Cereal == -1).sum()

name        0
mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       1
sugars      1
potass      2
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

### Drop 'name' column as it is not useful for this analysis.

In [6]:
Cereal = Cereal.drop('name', axis=1)

### Dispay the data after dropping the 'Name' column

In [7]:
Cereal

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

### Replace -1 with NaN using Numpy.

In [8]:
Cereal = Cereal.replace(-1, np.NaN)

### Use the .isna().sum() methods to determine the null fields in the data. This showed that carbo, sugars and potass have null fields.

In [9]:
Cereal.isna().sum()

mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       1
sugars      1
potass      2
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

### Iterate over columns to fill with fillna (mean of each)

In [10]:
for column in ['carbo','sugars','potass']:
    Cereal[column] = Cereal[column].fillna(Cereal[column].mean())

In [11]:
Cereal.isna().sum()

mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       0
sugars      0
potass      0
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

### Display the data after applying the fillna() method.

In [12]:
Cereal

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,N,C,70,4,1,130,10.0,5.0,6.0,280.000000,25,3,1.0,0.33,68.402973
1,Q,C,120,3,5,15,2.0,8.0,8.0,135.000000,0,3,1.0,1.00,33.983679
2,K,C,70,4,1,260,9.0,7.0,5.0,320.000000,25,3,1.0,0.33,59.425505
3,K,C,50,4,0,140,14.0,8.0,0.0,330.000000,25,3,1.0,0.50,93.704912
4,R,C,110,2,2,200,1.0,14.0,8.0,98.666667,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,G,C,110,2,1,250,0.0,21.0,3.0,60.000000,25,3,1.0,0.75,39.106174
73,G,C,110,1,1,140,0.0,13.0,12.0,25.000000,25,2,1.0,1.00,27.753301
74,R,C,100,3,1,230,3.0,17.0,3.0,115.000000,25,1,1.0,0.67,49.787445
75,G,C,100,3,1,200,3.0,17.0,3.0,110.000000,25,1,1.0,1.00,51.592193
76,G,C,110,2,1,200,1.0,16.0,8.0,60.000000,25,1,1.0,0.75,36.187559

### Convert the 'mfr','type' columns into list for smooth analysis.

In [13]:
{column: list(Cereal[column].unique()) for column in ['mfr','type']}

{'mfr': ['N', 'Q', 'K', 'R', 'G', 'P', 'A'], 'type': ['C', 'H']}

In [14]:
Cereal['type'] = Cereal['type'].apply(lambda x: 1 if x =='H' else 0)

### Create a DataFrame using Dummies for 'mfr' column to represent categorical data as numerical values

In [15]:
dummies = pd.get_dummies(Cereal['mfr'])
Cereal = pd.concat([Cereal, dummies], axis=1)
Cereal = Cereal.drop('mfr', axis=1)

### Display the data after applying 'Dummies'.

In [16]:
Cereal

,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,...,weight,cups,rating,A,G,K,N,P,Q,R
0,0,70,4,1,130,10.0,5.0,6.0,280.000000,25,...,1.0,0.33,68.402973,False,False,False,True,False,False,False
1,0,120,3,5,15,2.0,8.0,8.0,135.000000,0,...,1.0,1.00,33.983679,False,False,False,False,False,True,False
2,0,70,4,1,260,9.0,7.0,5.0,320.000000,25,...,1.0,0.33,59.425505,False,False,True,False,False,False,False
3,0,50,4,0,140,14.0,8.0,0.0,330.000000,25,...,1.0,0.50,93.704912,False,False,True,False,False,False,False
4,0,110,2,2,200,1.0,14.0,8.0,98.666667,25,...,1.0,0.75,34.384843,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,0,110,2,1,250,0.0,21.0,3.0,60.000000,25,...,1.0,0.75,39.106174,False,True,False,False,False,False,False
73,0,110,1,1,140,0.0,13.0,12.0,25.000000,25,...,1.0,1.00,27.753301,False,True,False,False,False,False,False
74,0,100,3,1,230,3.0,17.0,3.0,115.000000,25,...,1.0,0.67,49.787445,False,False,False,False,False,False,True
75,0,100,3,1,200,3.0,17.0,3.0,110.000000,25,...,1.0,1.00,51.592193,False,True,False,False,False,False,False
76,0,110,2,1,200,1.0,16.0,8.0,60.000000,25,...,1.0,0.75,36.187559,False,True,False,False,False,False,False

### Split & Scale

In [17]:
y = Cereal.loc[:, 'rating']
X = Cereal.drop('rating', axis=1)
X

,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,A,G,K,N,P,Q,R
0,0,70,4,1,130,10.0,5.0,6.0,280.000000,25,3,1.0,0.33,False,False,False,True,False,False,False
1,0,120,3,5,15,2.0,8.0,8.0,135.000000,0,3,1.0,1.00,False,False,False,False,False,True,False
2,0,70,4,1,260,9.0,7.0,5.0,320.000000,25,3,1.0,0.33,False,False,True,False,False,False,False
3,0,50,4,0,140,14.0,8.0,0.0,330.000000,25,3,1.0,0.50,False,False,True,False,False,False,False
4,0,110,2,2,200,1.0,14.0,8.0,98.666667,25,3,1.0,0.75,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,0,110,2,1,250,0.0,21.0,3.0,60.000000,25,3,1.0,0.75,False,True,False,False,False,False,False
73,0,110,1,1,140,0.0,13.0,12.0,25.000000,25,2,1.0,1.00,False,True,False,False,False,False,False
74,0,100,3,1,230,3.0,17.0,3.0,115.000000,25,1,1.0,0.67,False,False,False,False,False,False,True
75,0,100,3,1,200,3.0,17.0,3.0,110.000000,25,1,1.0,1.00,False,True,False,False,False,False,False
76,0,110,2,1,200,1.0,16.0,8.0,60.000000,25,1,1.0,0.75,False,True,False,False,False,False,False

### Displaying 'y' data after the drop() method to delete 'rating' column

In [18]:
y

0     68.402973
1     33.983679
2     59.425505
3     93.704912
4     34.384843
        ...
72    39.106174
73    27.753301
74    49.787445
75    51.592193
76    36.187559
Name: rating, Length: 77, dtype: float64

### Create the Scaler from the Scikit-Learn, a Preprocessing technique to standardize features by removing unit variance.

In [19]:
scaler = StandardScaler()
X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
X

,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,A,G,K,N,P,Q,R
0,-0.201347,-1.905397,1.337319,-0.012988,-0.356306,3.314439,-2.542013,-0.237495,2.627053,-0.14627,0.957813,-0.198067,-2.123870,-0.114708,-0.632456,-0.652630,3.439961,-0.363803,-0.340503,-0.340503
1,-0.201347,0.677623,0.417912,3.987349,-1.737087,-0.064172,-1.764055,0.225316,0.526376,-1.27255,0.957813,-0.198067,0.774053,-0.114708,-0.632456,-0.652630,-0.290701,-0.363803,2.936835,-0.340503
2,-0.201347,-1.905397,1.337319,-0.012988,1.204578,2.892113,-2.023374,-0.468901,3.206550,-0.14627,0.957813,-0.198067,-2.123870,-0.114708,-0.632456,1.532262,-0.290701,-0.363803,-0.340503,-0.340503
3,-0.201347,-2.938605,1.337319,-1.013072,-0.236238,5.003745,-1.764055,-1.625929,3.351425,-0.14627,0.957813,-0.198067,-1.388576,-0.114708,-0.632456,1.532262,-0.290701,-0.363803,-0.340503,-0.340503
4,-0.201347,0.161019,-0.501495,0.987096,0.484170,-0.486498,-0.208138,0.225316,0.000000,-0.14627,0.957813,-0.198067,-0.307262,-0.114708,-0.632456,-0.652630,-0.290701,-0.363803,-0.340503,2.936835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,-0.201347,0.161019,-0.501495,-0.012988,1.084510,-0.908824,1.607098,-0.931712,-0.560180,-0.14627,0.957813,-0.198067,-0.307262,-0.114708,1.581139,-0.652630,-0.290701,-0.363803,-0.340503,-0.340503
73,-0.201347,0.161019,-1.420902,-0.012988,-0.236238,-0.908824,-0.467457,1.150938,-1.067240,-0.14627,-0.251230,-0.198067,0.774053,-0.114708,1.581139,-0.652630,-0.290701,-0.363803,-0.340503,-0.340503
74,-0.201347,-0.355585,0.417912,-0.012988,0.844374,0.358155,0.569820,-0.931712,0.236628,-0.14627,-1.460273,-0.198067,-0.653283,-0.114708,-0.632456,-0.652630,-0.290701,-0.363803,-0.340503,2.936835
75,-0.201347,-0.355585,0.417912,-0.012988,0.484170,0.358155,0.569820,-0.931712,0.164191,-0.14627,-1.460273,-0.198067,0.774053,-0.114708,1.581139,-0.652630,-0.290701,-0.363803,-0.340503,-0.340503
76,-0.201347,0.161019,-0.501495,-0.012988,0.484170,-0.486498,0.310501,0.225316,-0.560180,-0.14627,-1.460273,-0.198067,-0.307262,-0.114708,1.581139,-0.652630,-0.290701,-0.363803,-0.340503,-0.340503

### Training & Testing the data. Training data takes more, 70% of the data, while the test takes 30%, using a random scale of 42.

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=42)

### Training suing LinearRegression, Ridge and Lasso

In [21]:
model = LinearRegression()
l2_model = Ridge(alpha=1.5)
l1_model = Lasso(alpha=0.001)

### Apply the fit() method to determine whether the data fit the model.

In [22]:
model.fit(X_train, y_train)
l2_model.fit(X_train, y_train)
l1_model.fit(X_train, y_train)

print("Models trained.")

Models trained.

### Restore Results on how fit data is after fitting the model to the data.

In [23]:
model_r2 = model.score(X_test, y_test)
l2_model_r2 = l2_model.score(X_test, y_test)
l1_model_r2 = l1_model.score(X_test, y_test)

### The R^2 Score evaluates the performance of Regression Models

In [24]:
print("R^2 Scores\n" + "*" * 10)
print("        Without Regularization:", model_r2)
print("With L2 (Ridge) Regularization:", l2_model_r2)
print("With L1 (Lasso) Regularization:", l1_model_r2)

R^2 Scores
**********
        Without Regularization: 0.9914187913729916
With L2 (Ridge) Regularization: 0.9936556858744913
With L1 (Lasso) Regularization: 0.9915110551266392